"""
JSON Schema generation for AST nodes.

Generates JSON Schema definitions for Suricata/Snort rule AST,
enabling validation and documentation of the JSON serialization format.

Licensed under GNU General Public License v3.0
Author: Marc Rivero | @seifreed | mriverolopez@gmail.com
"""

from __future__ import annotations

import json
from typing import Any

from pydantic import TypeAdapter

from surinort_ast.core.nodes import Rule
from surinort_ast.version import __ast_version__, __version__


class SchemaGenerator:
    """
    JSON Schema generator for AST nodes.

    Generates RFC-compliant JSON Schema from Pydantic models.

    Attributes:
        include_examples: Include example values in schema
        ref_template: JSON Schema $ref template format
    """

    def __init__(
        self,
        include_examples: bool = True,
        ref_template: str = "#/$defs/{model}",
    ) -> None:
        """
        Initialize the schema generator.

        Args:
            include_examples: Include example values in generated schema
            ref_template: Template for $ref paths (default uses $defs)
        """
        self.include_examples = include_examples
        self.ref_template = ref_template

    def generate_schema(
        self,
        title: str | None = None,
        description: str | None = None,
    ) -> dict[str, Any]:
        """
        Generate JSON Schema for Rule model.

        Args:
            title: Schema title (optional)
            description: Schema description (optional)

        Returns:
            JSON Schema dictionary (RFC 7159 compliant)

        Example:
            >>> generator = SchemaGenerator()
            >>> schema = generator.generate_schema()
            >>> print(json.dumps(schema, indent=2))
        """
        # Use TypeAdapter for schema generation
        adapter = TypeAdapter(Rule)

        # Generate schema with Pydantic v2
        schema = adapter.json_schema(
            ref_template=self.ref_template,
            mode="serialization",
        )

        # Add metadata
        if title:
            schema["title"] = title
        else:
            schema["title"] = "Surinort AST Rule Schema"

        if description:
            schema["description"] = description
        else:
            schema["description"] = (
                "JSON Schema for Suricata/Snort IDS rule Abstract Syntax Tree. "
                "Defines the structure for serialized rule AST nodes."
            )

        # Add version info
        schema["$comment"] = (
            f"Generated by surinort-ast v{__version__} (AST version {__ast_version__})"
        )

        # Add examples if requested
        if self.include_examples:
            schema["examples"] = self._generate_examples()

        return schema

    def generate_schema_json(
        self,
        title: str | None = None,
        description: str | None = None,
        indent: int | None = 2,
        **kwargs: Any,
    ) -> str:
        """
        Generate JSON Schema as formatted JSON string.

        Args:
            title: Schema title (optional)
            description: Schema description (optional)
            indent: JSON indentation (None for compact)
            **kwargs: Additional arguments for json.dumps

        Returns:
            JSON Schema as string

        Example:
            >>> generator = SchemaGenerator()
            >>> schema_json = generator.generate_schema_json()
        """
        schema = self.generate_schema(title=title, description=description)

        kwargs.setdefault("indent", indent)
        kwargs.setdefault("sort_keys", True)
        kwargs.setdefault("ensure_ascii", False)

        return json.dumps(schema, **kwargs)

    def generate_envelope_schema(
        self,
        title: str | None = None,
        description: str | None = None,
    ) -> dict[str, Any]:
        """
        Generate schema for metadata envelope.

        The envelope wraps rule(s) with metadata like ast_version and timestamp.

        Args:
            title: Schema title (optional)
            description: Schema description (optional)

        Returns:
            JSON Schema for metadata envelope

        Example:
            >>> generator = SchemaGenerator()
            >>> envelope_schema = generator.generate_envelope_schema()
        """
        # Get base rule schema
        rule_schema = self.generate_schema()

        # Create envelope schema
        return {
            "$schema": "https://json-schema.org/draft/2020-12/schema",
            "title": title or "Surinort AST Envelope Schema",
            "description": description
            or "Metadata envelope for serialized Suricata/Snort rule AST",
            "type": "object",
            "required": ["ast_version", "timestamp", "count", "data"],
            "properties": {
                "ast_version": {
                    "type": "string",
                    "description": "AST version identifier",
                    "pattern": r"^\d+\.\d+\.\d+$",
                    "examples": [__ast_version__],
                },
                "timestamp": {
                    "type": "string",
                    "format": "date-time",
                    "description": "ISO 8601 timestamp of serialization",
                },
                "count": {
                    "type": "integer",
                    "minimum": 1,
                    "description": "Number of rules in data payload",
                },
                "data": {
                    "oneOf": [
                        {
                            "description": "Single rule",
                            "$ref": "#/$defs/Rule",
                        },
                        {
                            "description": "Multiple rules",
                            "type": "object",
                            "required": ["rules"],
                            "properties": {
                                "rules": {
                                    "type": "array",
                                    "items": {"$ref": "#/$defs/Rule"},
                                    "description": "Array of rule objects",
                                }
                            },
                        },
                    ]
                },
            },
            "$defs": rule_schema.get("$defs", {}),
            "$comment": f"Generated by surinort-ast v{__version__}",
        }

    def _generate_examples(self) -> list[dict[str, Any]]:
        """
        Generate example rule objects for schema.

        Returns:
            List of example rule dictionaries
        """
        return [
            {
                "action": "alert",
                "header": {
                    "protocol": "tcp",
                    "src_addr": {"value": "any"},
                    "src_port": {"value": "any"},
                    "direction": "->",
                    "dst_addr": {"value": "any"},
                    "dst_port": {"value": 80},
                },
                "options": [
                    {"text": "HTTP Traffic", "node_type": "MsgOption"},
                    {"value": 1000001, "node_type": "SidOption"},
                    {"value": 1, "node_type": "RevOption"},
                ],
                "dialect": "suricata",
            }
        ]


# Convenience functions


def generate_schema(
    title: str | None = None,
    description: str | None = None,
    include_examples: bool = True,
) -> dict[str, Any]:
    """
    Generate JSON Schema for Rule model.

    Args:
        title: Schema title (optional)
        description: Schema description (optional)
        include_examples: Include example values

    Returns:
        JSON Schema dictionary

    Example:
        >>> from surinort_ast.serialization import generate_schema
        >>> schema = generate_schema()
    """
    generator = SchemaGenerator(include_examples=include_examples)
    return generator.generate_schema(title=title, description=description)


def generate_schema_json(
    title: str | None = None,
    description: str | None = None,
    include_examples: bool = True,
    indent: int | None = 2,
    **kwargs: Any,
) -> str:
    """
    Generate JSON Schema as formatted string.

    Args:
        title: Schema title (optional)
        description: Schema description (optional)
        include_examples: Include example values
        indent: JSON indentation
        **kwargs: Additional json.dumps arguments

    Returns:
        JSON Schema as string

    Example:
        >>> from surinort_ast.serialization import generate_schema_json
        >>> schema_str = generate_schema_json()
    """
    generator = SchemaGenerator(include_examples=include_examples)
    return generator.generate_schema_json(
        title=title,
        description=description,
        indent=indent,
        **kwargs,
    )


def generate_envelope_schema(
    title: str | None = None,
    description: str | None = None,
) -> dict[str, Any]:
    """
    Generate schema for metadata envelope.

    Args:
        title: Schema title (optional)
        description: Schema description (optional)

    Returns:
        JSON Schema for envelope

    Example:
        >>> from surinort_ast.serialization import generate_envelope_schema
        >>> envelope = generate_envelope_schema()
    """
    generator = SchemaGenerator()
    return generator.generate_envelope_schema(title=title, description=description)
