# Copyright (c) Marc Rivero López
# Licensed under GNU General Public License v3.0
# See LICENSE file for full terms
#
# ReadTheDocs Configuration for surinort-ast
# Documentation: https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

# Build configuration
build:
  os: ubuntu-24.04
  tools:
    python: "3.14"
  jobs:
    pre_install:
      # Install system dependencies if needed
      - echo "Installing system dependencies..."
    post_install:
      # Verify installation
      - python --version
      - pip list

# Python configuration
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - dev
    - requirements: requirements.txt
    - requirements: requirements-dev.txt

# MkDocs configuration
mkdocs:
  configuration: mkdocs.yml
  fail_on_warning: false

# Additional formats (PDF, ePub)
formats:
  - pdf
  - epub

# Search configuration
search:
  ranking:
    # Boost page titles more than content
    "api/*": -1
    "reference/*": 0
    "guides/*": 1
    "tutorials/*": 2
  ignore:
    - 404.html
    - search.html

# Subprojects (if any)
# submodules:
#   include: all
#   recursive: true
