ipvar HOME_NET any
ipvar EXTERNAL_NET any
ipvar DNS_SERVERS $HOME_NET
ipvar SMTP_SERVERS $HOME_NET
ipvar HTTP_SERVERS $HOME_NET
ipvar SQL_SERVERS $HOME_NET
ipvar TELNET_SERVERS $HOME_NET
ipvar SSH_SERVERS $HOME_NET
ipvar FTP_SERVERS $HOME_NET
ipvar SIP_SERVERS $HOME_NET

portvar HTTP_PORTS [80,81,311,383,591,593,901,1220,1414,1741,1830,2301,2381,2809,3037,3128,3702,4343,4848,5250,6988,7000,7001,7144,7145,7510,7777,7779,8000,8008,8014,8028,8080,8085,8088,8090,8118,8123,8180,8181,8243,8280,8300,8800,8888,8899,9000,9060,9080,9090,9091,9443,9999,11371,34443,34444,41080,50002,55555]
portvar SHELLCODE_PORTS !80
portvar ORACLE_PORTS 1024:
portvar SSH_PORTS 22
portvar FTP_PORTS [21,2100,3535]
portvar SIP_PORTS [5060,5061,5600]
portvar FILE_DATA_PORTS [$HTTP_PORTS,110,143]
portvar GTP_PORTS [2123,2152,3386]

var RULE_PATH /rules
var SO_RULE_PATH /rules
var PREPROC_RULE_PATH /rules
var WHITE_LIST_PATH /rules
var BLACK_LIST_PATH /rules

config disable_decode_alerts
config disable_tcpopt_experimental_alerts
config disable_tcpopt_obsolete_alerts
config disable_tcpopt_ttcp_alerts
config disable_tcpopt_alerts
config disable_ipopt_alerts
config policy_mode: inline

dynamicpreprocessor directory /usr/local/lib/snort_dynamicpreprocessor/
dynamicengine /usr/local/lib/snort_dynamicengine/libsf_engine.so
preprocessor stream5_global: track_tcp yes, track_udp yes
preprocessor stream5_tcp: policy windows, detect_anomalies
preprocessor stream5_udp: timeout 180
preprocessor ssl: ports { 443 465 563 636 989 992 993 994 995 5061 }

output alert_fast: stdout

config classification: attempted-admin, Attempted Administrator Privilege Gain, 1
config classification: attempted-dos, Attempted Denial of Service, 2
config classification: attempted-recon, Attempted Information Leak, 2
config classification: attempted-user, Attempted User Privilege Gain, 1
config classification: bad-unknown, Potentially Bad Traffic, 2
config classification: default-login-attempt, Default Account Attempted, 2
config classification: denial-of-service, Denial of Service, 1
config classification: misc-activity, Misc Activity, 3
config classification: misc-attack, Misc Attack, 2
config classification: network-scan, Network Scan, 3
config classification: non-standard-protocol, Non-Standard Protocol, 2
config classification: policy-violation, Potential Corporate Privacy Violation, 3
config classification: protocol-command-decode, Decode of an RPC Query, 3
config classification: rpc-portmap-decode, Decode of an RPC Query, 2
config classification: shellcode-detect, Executable Code was Detected, 1
config classification: string-detect, A Suspicious String was Detected, 3
config classification: successful-admin, Successful Administrator Privilege Gain, 1
config classification: successful-recon-limited, Successful Limited Information Leak, 2
config classification: successful-user, Successful User Privilege Gain, 1
config classification: suspicious-filename-detect, A Suspicious Filename was Detected, 2
config classification: suspicious-login, An Attempted User Privilege Gain, 2
config classification: system-call-detect, A System Call was Detected, 2
config classification: trojan-activity, A Network Trojan was Detected, 1
config classification: unknown, Unknown Traffic, 3
config classification: unsuccessful-user, Unsuccessful User Privilege Gain, 2
config classification: web-application-activity, Access to a Potentially Vulnerable Web Application, 3
config classification: web-application-attack, Web Application Attack, 1

include /rules/community.rules
