#!/usr/bin/env python3
"""
File Processing Examples for surinort-ast

This example demonstrates how to process rule files including:
- Reading rules from files
- Processing large rule sets
- Handling comments and blank lines
- Writing rules to files

Author: Marc Rivero | @seifreed
License: GPL v3.0
"""

import tempfile
from pathlib import Path

from surinort_ast import Dialect, parse_file, parse_rule, print_rule


def example_1_read_rules_file():
    """Read and parse rules from a file."""
    print("=" * 70)
    print("Example 1: Read Rules from File")
    print("=" * 70)

    # Create a temporary file with sample rules
    rules_content = """# Sample Suricata rules file
# Author: Security Team
# Date: 2024-01-15

# HTTP Detection Rules
alert http any any -> any any (msg:"HTTP GET Request"; flow:established,to_server; http_method; content:"GET"; sid:1000001; rev:1;)

# HTTPS Detection
alert tcp any any -> any 443 (msg:"HTTPS Traffic"; flow:established; sid:1000002; rev:1;)

# DNS Detection
alert udp any any -> any 53 (msg:"DNS Query"; sid:1000003; rev:1;)

# SSH Detection
alert tcp any any -> any 22 (msg:"SSH Connection Attempt"; flow:to_server; sid:1000004; rev:1;)
"""

    with tempfile.NamedTemporaryFile(mode="w", suffix=".rules", delete=False) as f:
        f.write(rules_content)
        temp_file = f.name

    print(f"\nReading rules from: {temp_file}\n")

    try:
        # Parse file
        rules = parse_file(temp_file)

        print(f"Successfully parsed {len(rules)} rules:")
        for i, rule in enumerate(rules, 1):
            # Get message and SID
            msg = "Unknown"
            sid = "Unknown"

            for opt in rule.options:
                if opt.node_type == "MsgOption":
                    msg = opt.text
                elif opt.node_type == "SidOption":
                    sid = opt.value

            print(f"  {i}. SID {sid}: {msg}")

            # Show origin information
            if rule.origin:
                print(f"     Source: line {rule.origin.line_number}")

    finally:
        # Cleanup
        Path(temp_file).unlink()


def example_2_handle_comments_and_blank_lines():
    """Demonstrate how comments and blank lines are handled."""
    print("\n" + "=" * 70)
    print("Example 2: Comments and Blank Lines Handling")
    print("=" * 70)

    rules_content = """
# This is a comment
alert tcp any any -> any 80 (msg:"Rule 1"; sid:1;)

    # Indented comment

alert tcp any any -> any 443 (msg:"Rule 2"; sid:2;)


# Another comment with blank lines above

alert tcp any any -> any 22 (msg:"Rule 3"; sid:3;)
"""

    with tempfile.NamedTemporaryFile(mode="w", suffix=".rules", delete=False) as f:
        f.write(rules_content)
        temp_file = f.name

    print(f"\nFile content has {len(rules_content.splitlines())} lines total")

    try:
        rules = parse_file(temp_file)
        print(f"Parsed {len(rules)} actual rules (comments and blank lines ignored)\n")

        for rule in rules:
            if rule.origin:
                print(f"  Line {rule.origin.line_number}: {print_rule(rule)[:60]}...")

    finally:
        Path(temp_file).unlink()


def example_3_write_rules_to_file():
    """Write rules to a file."""
    print("\n" + "=" * 70)
    print("Example 3: Write Rules to File")
    print("=" * 70)

    # Create some rules programmatically
    rules_text = [
        'alert tcp any any -> any 80 (msg:"HTTP Traffic"; sid:1000001; rev:1;)',
        'alert tcp any any -> any 443 (msg:"HTTPS Traffic"; sid:1000002; rev:1;)',
        'alert udp any any -> any 53 (msg:"DNS Query"; sid:1000003; rev:1;)',
    ]

    rules = [parse_rule(text) for text in rules_text]

    # Write to temporary file
    with tempfile.NamedTemporaryFile(mode="w", suffix=".rules", delete=False) as f:
        # Write header comment
        f.write("# Generated by surinort-ast\n")
        f.write("# Auto-generated rules file\n\n")

        # Write rules
        for rule in rules:
            rule_text = print_rule(rule)
            f.write(rule_text + "\n")

        temp_file = f.name

    print(f"\nWrote {len(rules)} rules to: {temp_file}\n")

    # Read back and verify
    print("Verifying written file:")
    with open(temp_file) as f:
        lines = f.readlines()
        print(f"  Total lines: {len(lines)}")
        print("\nFile contents:")
        print("  " + "-" * 60)
        for line in lines:
            print(f"  {line.rstrip()}")
        print("  " + "-" * 60)

    # Cleanup
    Path(temp_file).unlink()


def example_4_process_large_file_streaming():
    """Process large files in streaming fashion."""
    print("\n" + "=" * 70)
    print("Example 4: Streaming Processing of Large Files")
    print("=" * 70)

    # Create a larger file
    num_rules = 100

    with tempfile.NamedTemporaryFile(mode="w", suffix=".rules", delete=False) as f:
        f.write("# Large rules file\n\n")

        for i in range(1, num_rules + 1):
            port = 1000 + i
            f.write(f'alert tcp any any -> any {port} (msg:"Rule {i}"; sid:{i}; rev:1;)\n')

        temp_file = f.name

    print(f"\nProcessing file with {num_rules} rules in streaming mode...\n")

    try:
        # Streaming approach: process line by line
        rule_count = 0
        error_count = 0
        protocol_stats = {}

        with open(temp_file) as f:
            for line_num, line in enumerate(f, 1):
                line = line.strip()

                # Skip comments and blank lines
                if not line or line.startswith("#"):
                    continue

                try:
                    rule = parse_rule(line)
                    rule_count += 1

                    # Collect statistics
                    protocol = rule.header.protocol.value
                    protocol_stats[protocol] = protocol_stats.get(protocol, 0) + 1

                except Exception as e:
                    error_count += 1
                    print(f"  Error on line {line_num}: {str(e)[:50]}...")

        print("Streaming results:")
        print(f"  Processed: {rule_count} rules")
        print(f"  Errors: {error_count}")
        print("\n  Protocol distribution:")
        for protocol, count in sorted(protocol_stats.items()):
            print(f"    {protocol}: {count}")

    finally:
        Path(temp_file).unlink()


def example_5_multi_dialect_files():
    """Handle files with different dialects."""
    print("\n" + "=" * 70)
    print("Example 5: Multi-Dialect File Processing")
    print("=" * 70)

    # Suricata rules
    suricata_content = """# Suricata rules
alert http any any -> any any (msg:"Suricata HTTP"; flow:established; sid:1;)
alert tls any any -> any any (msg:"Suricata TLS"; tls.sni; sid:2;)
"""

    # Snort2 rules
    snort2_content = """# Snort2 rules
alert tcp any any -> any 80 (msg:"Snort2 HTTP"; flow:established; sid:3;)
alert tcp any any -> any 443 (msg:"Snort2 HTTPS"; flow:established; sid:4;)
"""

    print("\nProcessing Suricata rules:")
    with tempfile.NamedTemporaryFile(mode="w", suffix=".rules", delete=False) as f:
        f.write(suricata_content)
        temp_file1 = f.name

    try:
        rules = parse_file(temp_file1, dialect=Dialect.SURICATA)
        print(f"  Parsed {len(rules)} Suricata rules")
    finally:
        Path(temp_file1).unlink()

    print("\nProcessing Snort2 rules:")
    with tempfile.NamedTemporaryFile(mode="w", suffix=".rules", delete=False) as f:
        f.write(snort2_content)
        temp_file2 = f.name

    try:
        rules = parse_file(temp_file2, dialect=Dialect.SNORT2)
        print(f"  Parsed {len(rules)} Snort2 rules")
    finally:
        Path(temp_file2).unlink()


def example_6_file_with_errors():
    """Handle files with some invalid rules."""
    print("\n" + "=" * 70)
    print("Example 6: File with Parse Errors")
    print("=" * 70)

    mixed_content = """# Mixed valid and invalid rules
alert tcp any any -> any 80 (msg:"Valid rule 1"; sid:1;)
invalid rule here
alert tcp any any -> any 443 (msg:"Valid rule 2"; sid:2;)
another bad rule
alert tcp any any -> any 22 (msg:"Valid rule 3"; sid:3;)
"""

    with tempfile.NamedTemporaryFile(mode="w", suffix=".rules", delete=False) as f:
        f.write(mixed_content)
        temp_file = f.name

    print("\nProcessing file with mixed valid/invalid rules...\n")

    try:
        # parse_file continues on errors
        rules = parse_file(temp_file)

        print("Results:")
        print(f"  Successfully parsed: {len(rules)} rules")

        # Show what was parsed
        print("\n  Parsed rules:")
        for rule in rules:
            for opt in rule.options:
                if opt.node_type == "SidOption":
                    print(
                        f"    SID {opt.value}: Line {rule.origin.line_number if rule.origin else 'unknown'}"
                    )

    except Exception as e:
        print(f"Error: {e}")

    finally:
        Path(temp_file).unlink()


def example_7_organized_output():
    """Write rules to file with organization."""
    print("\n" + "=" * 70)
    print("Example 7: Organized Rule Output")
    print("=" * 70)

    from collections import defaultdict

    rules_text = [
        'alert tcp any any -> any 80 (msg:"HTTP Attack"; classtype:web-application-attack; sid:1;)',
        'alert tcp any any -> any 443 (msg:"HTTPS Attack"; classtype:web-application-attack; sid:2;)',
        'drop tcp any any -> any 22 (msg:"SSH Block"; classtype:attempted-admin; sid:3;)',
        'alert udp any any -> any 53 (msg:"DNS Query"; classtype:protocol-command-decode; sid:4;)',
    ]

    rules = [parse_rule(text) for text in rules_text]

    # Group by classtype
    by_classtype = defaultdict(list)
    for rule in rules:
        classtype = None
        for opt in rule.options:
            if opt.node_type == "ClasstypeOption":
                classtype = opt.value
                break

        by_classtype[classtype or "uncategorized"].append(rule)

    # Write organized output
    with tempfile.NamedTemporaryFile(mode="w", suffix=".rules", delete=False) as f:
        f.write("# Organized Rules File\n")
        f.write("# Generated by surinort-ast\n\n")

        for classtype, rules_group in sorted(by_classtype.items()):
            f.write(f"# {classtype.upper()}\n")
            for rule in rules_group:
                f.write(print_rule(rule) + "\n")
            f.write("\n")

        temp_file = f.name

    print(f"\nWrote organized rules to: {temp_file}\n")
    print("File structure:")

    with open(temp_file) as f:
        for line in f:
            if line.strip():
                print(f"  {line.rstrip()}")

    Path(temp_file).unlink()


def main():
    """Run all examples."""
    print("\n" + "=" * 70)
    print("SURINORT-AST: File Processing Examples")
    print("=" * 70)
    print("\nDemonstrating file I/O operations for IDS rules.\n")

    try:
        example_1_read_rules_file()
        example_2_handle_comments_and_blank_lines()
        example_3_write_rules_to_file()
        example_4_process_large_file_streaming()
        example_5_multi_dialect_files()
        example_6_file_with_errors()
        example_7_organized_output()

        print("\n" + "=" * 70)
        print("All examples completed successfully!")
        print("=" * 70)

    except Exception as e:
        print(f"\nError: {e}")
        import traceback

        traceback.print_exc()
        return 1

    return 0


if __name__ == "__main__":
    exit(main())
