"""Render conformance JSON reports as a public Markdown dashboard."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


def _report_rows(report: dict[str, Any], source: str) -> list[dict[str, Any]]:
    if isinstance(report.get("engines"), list):
        rows: list[dict[str, Any]] = []
        for entry in report["engines"]:
            nested = entry.get("report")
            if isinstance(nested, dict):
                rows.extend(_report_rows(nested, f"{source}:{entry.get('id', 'engine')}"))
        return rows
    return [
        {
            "source": source,
            "version": report.get("package_version"),
            "dialect": report.get("dialect", ", ".join(report.get("dialects", []))),
            "total_rules": report.get("total_rules", 0),
            "parse_rate": report.get("parse_rate"),
            "round_trip_rate": report.get("round_trip_rate"),
            "unexpected_failures": report.get("unexpected_failures", 0),
            "rules_per_second": report.get("rules_per_second"),
            "peak_memory_mb": report.get("peak_memory_mb"),
        }
    ]


def _load_reports(history_dir: Path, report: Path | None) -> list[dict[str, Any]]:
    paths = sorted(history_dir.glob("*.json")) if history_dir.is_dir() else []
    if report is not None:
        paths.append(report)
    rows: list[dict[str, Any]] = []
    for path in paths:
        payload = json.loads(path.read_text(encoding="utf-8"))
        if isinstance(payload, dict):
            rows.extend(_report_rows(payload, path.name))
    return rows


def render(history_dir: Path, output: Path, report: Path | None = None) -> str:
    """Render reports and write the resulting Markdown page."""
    rows = _load_reports(history_dir, report)
    lines = [
        "# Conformance Dashboard",
        "",
        "This page contains only reports generated by the conformance lab. "
        "Missing engine runs are not represented as passing results.",
        "",
        "| Snapshot | Version | Dialect | Rules | Parse rate | Round-trip rate | Unexpected failures | Rules/s | Peak MB |",
        "| --- | --- | --- | ---: | ---: | ---: | ---: | ---: | ---: |",
    ]
    if rows:
        for row in rows:

            def number(value: Any) -> str:
                return "-" if value is None else str(value)

            lines.append(
                "| {source} | {version} | {dialect} | {total_rules} | {parse_rate} | "
                "{round_trip_rate} | {unexpected_failures} | {rules_per_second} | "
                "{peak_memory_mb} |".format(**{key: number(value) for key, value in row.items()})
            )
    else:
        lines.append("| No reports | - | - | 0 | - | - | - | - | - |")
    lines.extend(
        [
            "",
            "Rates are fractions in the source JSON. Engine and PCAP behavior "
            "claims require a report from the corresponding real engine build.",
            "",
        ]
    )
    rendered = "\n".join(lines)
    output.write_text(rendered, encoding="utf-8")
    return rendered


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--history-dir", type=Path, required=True)
    parser.add_argument("--report", type=Path)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    render(args.history_dir, args.output, args.report)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
